---
title: "Stat_101_B_Project_Report"
output: pdf_document
---
```{r}
# Q1
# Group name: "H&K"
# Group members: Jingun Kwon "sstylenote91@gmail.com"
#               Junhyuk Jang "junhyuk.jang0@gmail.com"
#               Ka Ying Mok  "kmok850@g.ucla.edu"
#               Myungwoo Nam "myungwoo0221@gmail.com"
```
```{r}
# Q2
#Our research question was whether glucose has an effect on the performance of 
#swimming 50 meters with freestyle. We had 4 age groups consisting of people in 
#their 10s, 20s, 30s and 40s.  we measured the difference in performance corresponding 
#to the different doses. We thought that glucose would enhance the performance 
#because in the medical world glucose is used to help sick people. 
#Specifically, glucose is administered to people who are suffering from severe 
#colds and the patients generally get better. This implies that glucose helps 
#people gain energy and from this we thought that glucose would improve a person’s
#physical performance. Specifically, we wanted to see if a 5%, and 10% glucose 
#dose would shorten the time it would take for a person to finish the 50-meter 
#swimming course with freestyle. To investigate this question, we are going to 
#conduct a completely randomized experiment with blocking in order to reduce the 
#variation in error, which will increase precision of estimates and the power 
#of hypothesis testing. In terms of control groups, we are going to set people 
#who got injected glucose 5% dosage and 10% dosage and set uncontrolled group 
#as people without injected glucose. we are going to collect our data 
#by using the island website.
```
```{r}
# We will conduct our experiment with 40 randomly chosen samples with confidence 
#level of 95% and then make them swim 50m freestyle without glucose and with a 
#5% dose and a 10% dose of glucose. since we are interested in whether glucose 
#dosage affects the mean time ofswimming freestyle 50m, our null and 
#alternative hypothesis would be:

# Ho:There is no significant difference of swimming time at 50m regardless of 
# glucose level.
# H1:At least one of glucose levels will yield the significaly differnt 
# mean time of swimming 50m.

# We will use age as a block because we intuitively know age is a nuisance 
#factor which can influenceour response variable because a person’s 
#athletic capability deteriorates with age. We will investigate
# whether blocking age will give us noise deducted effect. In other words, 
# we will investigate whether or not blocking is statistically significant.
# We will divide ages into 10~19 as 10's,20~29 as 20's, 30~39 as 30'sand 
#40~49 as 40's.
# Our another null and alternative hypothesis would be:

# Ho:There is no sigfinificant difference of swimming time at 50m between age groups.
# H1:There is sigfinificant difference of swimming time at 50m between age groups.

```
```{r}
# Q3 Collect your data. Include a small subset of your data in this report.

  #   attch the data.

#First of all, all cities in the Island are numbered in order and only one 
#city named Vardo is selected by the sampling function in R studio randomly. 
#We searched for 40 people whose ages are from 10 to 49 in the city. 
#The ages are divided into 4 groups, which are 10’s, 20’s, 30’s and 40’s. 
#Each groups have 10 people. We only considered households that had people 
#of the desired age groups. (e.g. 10~19) After selecting these specific
#households we randomly selected our dataset from these targeted samples.
#After we collected the data, we made each person swim freestyle 50m without
#glucose and with glucose 5% and 10% step by step


```
```{r}
# Q4 
#      draw diagnostic plot and  show that our assumption not violated 

data=c(63.57,51.76,51.26,61.42,60.37,51.69,53.38,58.22,61.06,52.65,51.1,58.28)
df<-data.frame
glucose<-c("0%","5%","10%")
ages_blocking<-c("10's","20's","30,s","40's")
df<-data.frame(glucose,data, ages_blocking)
df
summary(aov(data~ages_blocking+glucose, data=df))

# conduct anova without blocking and show how huge the difference is.


# From ANOVA table, p-value for treatment is equal to 0.00232 which is smaller than 
# alpha(0.05). We decide to reject the null hypotheis and conclude that at least
# one of glucose level yield  differnt mean time swimming 50m. Further investigation
# required to see which dosage level significantly different from which.

# We are going to use Turkey method to investigate.
# t1 = mean time swimming 50m without glucose
# t2 = mean time swimming 50m with 5% glucose.
# t3 = mean time swimming 50m with 10% glucose.
t12=(55.36-57.75)/(sqrt( 0.36)*sqrt(0.5))
abs(t12)
# abs(t12) > 3.068274 implies that mean time swimming 50m witout glucose and with 5% is 
# significantly different.
t13=(55.57-57.75)/(sqrt( 0.36)*sqrt(1/2))
abs(t13)
# abs(t13) > 3.068274 implies that mean time swimming 50m witout glucose and with 10% is 
# significantly different.
t23=(55.57-55.36)/(sqrt( 0.36)*sqrt(1/2))
abs(t23)
# abs(t23) < 3.068274 implies that mean time swimming 50m with 5%glucose and with 10% is 
# not significantly different.
(1/sqrt(2))*qtukey(1-0.05,3,6)

# By looking at the result achieved by turkey method, we can conclude that if 
# we injecta dosage of glucose it significantly reduces the mean time of swimming 
# 50 meters but the level of dosage (whether it is 5% or 10%) does not have 
# a significant impact. In other words, glucose injection does improve physical 
# performance but more and more glucose injection does not guarantee us 
# to get shorten mean time swimming.


```
