---
title: "datafest"
author: "Sang Ok Suh"
date: "April 28, 2018"
output: html_document
---

```{r}
## Subsetting
df1 <- df
df1$notlocal = df1$clicks-df1$localClicks
df2 <- df1 %>% group_by(jobId) %>% summarise(mean.clicks = mean(clicks), 
                                             mean.localclicks = mean(localClicks),
                                             mean.notlocal = mean(notlocal),
                                             maxdays = which.max(jobAgeDays) + 1,
                                             totalclicks = mean.clicks*maxdays,
                                             total.local = mean.localclicks*maxdays,
                                             total.notlocal = mean.notlocal*maxdays) 

df3 <- df1 %>% group_by(jobId) %>% slice(which.max(jobAgeDays))

df5 <- left_join(df3, df2, by = "jobId")

bagel <- df5
```

```{r}
bagel$totallevel[bagel$mean.clicks <= 15.44444] <- "Low"
bagel$totallevel[bagel$mean.clicks > 15.44444 & bagel$mean.clicks < 22.07143] <- "Medium"
bagel$totallevel[bagel$mean.clicks >= 22.07143] <- "High"

table(bagel$totallevel)

bagel$locallevel[bagel$mean.localclicks <= 1.275000] <- "Low"
bagel$locallevel[bagel$mean.localclicks > 1.275000 & bagel$mean.localclicks < 3.217391] <- "Medium"
bagel$locallevel[bagel$mean.localclicks >= 3.217391] <- "High"

bagel$notlocal_level[bagel$mean.notlocal <= 13.37500] <- "Low"
bagel$notlocal_level[bagel$mean.notlocal > 13.37500 & bagel$mean.notlocal < 18.40909] <- "Medium"
bagel$notlocal_level[bagel$mean.notlocal >= 18.40909] <- "High"

bagel$experienceLevel <- "NA"
bagel$experienceLevel[bagel$experienceRequired>=0] <- "High"
bagel$experienceLevel[bagel$experienceRequired<5] <- "Medium"
bagel$experienceLevel[bagel$experienceRequired<2] <- "Low"


bagel$totallevel <- as.factor(bagel$totallevel)
bagel$locallevel <- as.factor(bagel$locallevel)
bagel$notlocal_level <- as.factor(bagel$notlocal_level)
bagel$experienceLevel <- as.factor(bagel$experienceLevel)

bagel$ratio.local <-bagel$total.local/ bagel$totalclicks
bagel$ratio.nonlocal <- bagel$total.notlocal / bagel$totalclicks
```

```{r}
write.csv(bagel,"bagel.csv", row.names = FALSE)
```

```{r}
usbagel <- bagel[bagel$country == "US",]
```

```{r}
usbagel <- usbagel[usbagel$educationRequirements != "", ]
usbagel <- usbagel[usbagel$supervisingJob != "", ]

usbagel$experienceLevel <- "NA"
usbagel$experienceLevel[usbagel$experienceRequired==0] <- "A"
usbagel$experienceLevel[usbagel$experienceRequired>0] <- "B"
usbagel$experienceLevel[usbagel$experienceRequired>2] <- "C"
usbagel$experienceLevel[usbagel$experienceRequired>5] <- "D"
usbagel$experienceLevel[usbagel$experienceRequired>15] <- "E"

abc <- usbagel

write.csv(abc, "abc.csv", row.names = FALSE)
```

```{r}
#divide data
library(dplyr)
abc$experienceLevel <- as.character(abc$experienceLevel)
abc$experienceLevel[is.na(abc$experienceLevel)] <- "NA"
abc$experienceLevel <- as.factor(abc$experienceLevel)
expA = abc[abc$experienceLevel == "A",]
expB = abc[abc$experienceLevel == "B",]
expC = abc[abc$experienceLevel == "C",]
expD = abc[abc$experienceLevel == "D",]
expE = abc[abc$experienceLevel == "E",]
expna = abc[abc$experienceLevel == "NA",]

library(ggplot2)


```

```{r}
#all groups
ggplot(abc,aes(x=ratio.local,group=experienceLevel,fill=experienceLevel))+
  geom_histogram(position="identity",alpha=0.3,binwidth=0.05)+theme_bw()

par(mfrow=c(3,2))

#all types
ggplot(abc,aes(x=ratio.local, fill=experienceLevel))+geom_histogram()+facet_grid(~experienceLevel)+theme_bw() + facet_wrap(~experienceLevel)

abc.1 <- abc[abc$experienceLevel != "NA",]

ggplot(abc.1,aes(x=ratio.local,fill=experienceLevel))+geom_histogram()+facet_grid(~experienceLevel)+theme_bw() + facet_wrap(~experienceLevel)

```
```{r}
management <- abc[abc$normTitleCategory=="management",]
mednurse <- abc[abc$normTitleCategory=="mednurse",]
techsoftware <- abc[abc$normTitleCategory=="techsoftware",]
sales <- abc[abc$normTitleCategory=="sales",]
install <- abc[abc$normTitleCategory=="instsall",]
admin <- abc[abc$normTitleCategory=="admin",]
driver <- abc[abc$normTitleCategory=="driver",]
retail <- abc[abc$normTitleCategory=="retail",]
accounting <- abc[abc$normTitleCategory=="accounting",]
food <- abc[abc$normTitleCategory=="food",]
```

```{r}
library(lubridate)
abc$date <- as.Date(abc$date)
abc$startdate <- abc$date - abc$maxdays
```

