---
title: "STAT_101C_FINAL_CODE"
author: "K3"
date: "6/15/2017"
output: pdf_document
---
```{r}
# Group name: K3
# Jingun Kwon: stylenote91@gmail.com 
# Junhyuk Jang: junhyuk.jang0@gmail.com
# Myungwoo Nam: myungwoo0221@gmail.com

```

```{r}
# This is how we cleaned our data. 
# Lowest MSE model data cleaning (lm + polynomial degreee of 5)
test<- read.csv("~/Downloads/testing.without.response.txt")
train <- read.csv("~/Downloads/lafdtraining updated (1).csv")
library(class)
library(FNN)
library(KRLS)




attach(train)
attach(test)
train=train[,-c(1:2)]
train=train[complete.cases(train),]

train <- subset(train,!(train$elapsed_time[Incident.Creation.Time..GMT.] > quantile(train$elapsed_time[Incident.Creation.Time..GMT.], probs=c(.01, .99))[2] | train$elapsed_time[Incident.Creation.Time..GMT.] < quantile(train$elapsed_time[Incident.Creation.Time..GMT.], probs=c(.01, .99))[1]) )
train <- subset(train,!(train$elapsed_time[year] > quantile(train$elapsed_time[year], probs=c(.01, .99))[2] | train$elapsed_time[year] < quantile(train$elapsed_time[year], probs=c(.01, .99))[1]) ) 
train <- subset(train,!(train$elapsed_time[Dispatch.Sequence] > quantile(train$elapsed_time[Dispatch.Sequence], probs=c(.01, .99))[2] | train$elapsed_time[Dispatch.Sequence] < quantile(train$elapsed_time[Dispatch.Sequence], probs=c(.01, .99))[1]) ) 
train <- subset(train,!(train$elapsed_time[PPE.Level] > quantile(train$elapsed_time[PPE.Level], probs=c(.01, .99))[2] | train$elapsed_time[PPE.Level] < quantile(train$elapsed_time[PPE.Level], probs=c(.01, .99))[1]) )


train <- subset(train,!(train$elapsed_time[Dispatch.Sequence] > quantile(train$elapsed_time[Dispatch.Sequence], probs=c(.01, .99))[2] | train$elapsed_time[Dispatch.Sequence] < quantile(train$elapsed_time[Dispatch.Sequence], probs=c(.01, .99))[1]) )

train <- subset(train,!(train$elapsed_time[Unit.Type] > quantile(train$elapsed_time[Unit.Type], probs=c(.01, .99))[2] | train$elapsed_time[Unit.Type] < quantile(train$elapsed_time[Unit.Type], probs=c(.01, .99))[1]) )




train$year=as.factor(train$year)
train$First.in.District=as.factor(train$First.in.District)
train$Dispatch.Sequence=as.numeric(train$Dispatch.Sequence)
train$Incident.Creation.Time..GMT.=as.numeric(train$Incident.Creation.Time..GMT.)

train=train[,-3]
View(train)
str(train$Dispatch.Status)
str(test$Dispatch.Status)

View(test)

test=test[,-c(2)]

test$Incident.Creation.Time..GMT.=as.numeric(test$Incident.Creation.Time..GMT.)
test$year=as.factor(test$year)
test$Dispatch.Status=as.factor(test$Dispatch.Status)
test$First.in.District=as.factor(test$First.in.District)
test=test[,-4]
test[is.na(test$Dispatch.Sequence),]$Dispatch.Sequence= mean(test$Dispatch.Sequence,na.rm = T)
test[test$Unit.Type=="RP - Rehab Plug Buggy",]$Unit.Type="RA - ALS Rescue Ambulance"


head(train)
head(test)
#5 factors , 2 continuous


###
##

sub_index=sample(1:nrow(train),size = length(train$year), replace=F)
subdat=train[sub_index,]
subtrain_index=sample(1:nrow(subdat),size = nrow(subdat)/2,replace = F)
subtrain=subdat[subtrain_index,]
subtest=subdat[-subtrain_index,]

ptm<-proc.time()
fitpoly=lm(elapsed_time~year+Dispatch.Status+Unit.Type+PPE.Level+First.in.District
           +polym(Dispatch.Sequence,log(Incident.Creation.Time..GMT.),degree=5,raw=T),data=subdat)
proc.time()-ptm

lmpre=predict(fitpoly,test)

submit<-data.frame(row.id = test$row.id, elapsed_time = lmpre)
write.csv(submit,file = "gg.csv",row.names = F)
gg <- read.csv("~/gg.csv")

names(gg)[2] <- paste("prediction")

write.csv(gg,file = "gg.csv",row.names = F)
###
```
```{r}
# Additionally, we have tried many times to change and manipulate the data set 
# in order to improve our kaggle score. For instance, we searched each fire station
# district in LA and the dispatch time, arrival time and response time of the station
# district are replaced with the mean time of each variables. In addition, 
# we also tried to drop the levels of dispatch.status. The HSP,NAV and ONS levels of 
# Dispatch.Status are merged to ENR,TSP and AVI. Also, we include zip-code of 
# all the firestation and see whether is significant effect on elapsed time.
# Even if we tried with those ways, it was not influenced on our kaggle score change. 
# We have submitted 30 times with different algorithms and different ways of data cleaning.
# However, we could not get the result that we are satisfied with. 
# Even though our group could not reach to the goal, from this group project, 
# we have learned how to deal with large data set as well as how to cooperate 
# and work together. We have discussed together.

# (1) When it comes to data cleaning we first replaced all the outlier to
# the median value of that variable.
# data with outliers = median
# elapsed time
median(df$elapsed_time)
upperw <- boxplot.stats(df_train$elapsed_time)$stats[5]
filter <- df$elapsed_time > upperw
head(filter,100)
df$elapsed_time[filter] <- upperw
# First in district
median(df$norm_First_District)
upperw <- boxplot.stats(df_train$norm_First_District)$stats[5]
filter <- df$norm_First_District < upperw
df$norm_First_District[filter == "False"] <-NA
df$norm_First_District[df$elapsed_time == "0"] <- 0.1443542
head(df$norm_First_District,100)
# Dispatch seqence
median(df$norm_Dispatch_Seq)
upperw <- boxplot.stats(df_train$norm_Dispatch_Seq)$stats[5]
filter <- df$norm_Dispatch_Seq < upperw
df$norm_Dispatch_Seq[filter == "False"] <-NA
df$norm_Dispatch_Seq[df$elapsed_time == "0"] <- -0.07658898
head(df$norm_Dispatch_Seq,100)    
# Incident Time
median(df$norm_Incident_Time)
upperw <- boxplot.stats(df_train$norm_Incident_Time)$stats[5]
filter <- df$norm_Incident_Time < upperw
df$norm_Incident_Time[filter == "False"] <-NA
df$norm_Incident_Time[df$elapsed_time == "0"] <- 0.1901404
head(df$norm_Incident_Time,100)      

# - We found external data from the LAFD open data website 
# and add the average traveled time depend on EMS and Non-EMS for the 
# each district of the fire station
# EMS
train$avg_travel_time[First.in.District == "1" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "1"])
train$avg_travel_time[First.in.District == "2" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "2"])
train$avg_travel_time[First.in.District == "3" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "3"])
train$avg_travel_time[First.in.District == "4" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "4"])
train$avg_travel_time[First.in.District == "5" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "5"])
train$avg_travel_time[First.in.District == "6" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "6"])
train$avg_travel_time[First.in.District == "7" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "7"])
train$avg_travel_time[First.in.District == "8" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "8"])
train$avg_travel_time[First.in.District == "9" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "9"])
train$avg_travel_time[First.in.District == "10" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "10"])
train$avg_travel_time[First.in.District == "11" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "11"])
train$avg_travel_time[First.in.District == "12" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "12"])
train$avg_travel_time[First.in.District == "13" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "13"])
train$avg_travel_time[First.in.District == "14" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "14"])
train$avg_travel_time[First.in.District == "15" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "15"])
train$avg_travel_time[First.in.District == "16" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "16"])
train$avg_travel_time[First.in.District == "17" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "17"])
train$avg_travel_time[First.in.District == "18" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "18"])
train$avg_travel_time[First.in.District == "19" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "19"])
train$avg_travel_time[First.in.District == "20" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "20"])
train$avg_travel_time[First.in.District == "21" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "21"])

train$avg_travel_time[First.in.District == "23" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "23"])
train$avg_travel_time[First.in.District == "24" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "24"])
train$avg_travel_time[First.in.District == "25" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "25"])
train$avg_travel_time[First.in.District == "26" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "26"])

train$avg_travel_time[First.in.District == "28" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "28"])
train$avg_travel_time[First.in.District == "29" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "29"])

train$avg_travel_time[First.in.District == "33" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "33"])
train$avg_travel_time[First.in.District == "34" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "34"])
train$avg_travel_time[First.in.District == "35" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "35"])
train$avg_travel_time[First.in.District == "36" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "36"])
train$avg_travel_time[First.in.District == "37" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "37"])
train$avg_travel_time[First.in.District == "38" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "38"])
train$avg_travel_time[First.in.District == "39" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "39"])

train$avg_travel_time[First.in.District == "41" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "41"])
train$avg_travel_time[First.in.District == "42" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "42"])
train$avg_travel_time[First.in.District == "43" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "43"])
train$avg_travel_time[First.in.District == "44" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "44"])

train$avg_travel_time[First.in.District == "46" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "46"])
train$avg_travel_time[First.in.District == "47" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "47"])

train$avg_travel_time[First.in.District == "55" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "55"])
train$avg_travel_time[First.in.District == "56" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "56"])
train$avg_travel_time[First.in.District == "57" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "57"])

train$avg_travel_time[First.in.District == "58" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "58"])
train$avg_travel_time[First.in.District == "59" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "59"])
train$avg_travel_time[First.in.District == "60" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "60"])
train$avg_travel_time[First.in.District == "61" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "61"])
train$avg_travel_time[First.in.District == "62" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "62"])
train$avg_travel_time[First.in.District == "63" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "63"])
train$avg_travel_time[First.in.District == "64" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "64"])

train$avg_travel_time[First.in.District == "65" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "65"])
train$avg_travel_time[First.in.District == "66" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "66"])
train$avg_travel_time[First.in.District == "67" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "67"])
train$avg_travel_time[First.in.District == "68" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "68"])
train$avg_travel_time[First.in.District == "69" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "69"])
train$avg_travel_time[First.in.District == "70" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "70"])
train$avg_travel_time[First.in.District == "71" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "71"])
train$avg_travel_time[First.in.District == "72" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "72"])
train$avg_travel_time[First.in.District == "73" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "73"])
train$avg_travel_time[First.in.District == "74" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "74"])
train$avg_travel_time[First.in.District == "75" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "75"])
train$avg_travel_time[First.in.District == "76" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "76"])
train$avg_travel_time[First.in.District == "77" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "77"])

train$avg_travel_time[First.in.District == "78" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "78"])
train$avg_travel_time[First.in.District == "79" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "79"])
train$avg_travel_time[First.in.District == "80" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "80"])

train$avg_travel_time[First.in.District == "81" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "81"])
train$avg_travel_time[First.in.District == "82" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "82"])
train$avg_travel_time[First.in.District == "83" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "83"])
train$avg_travel_time[First.in.District == "84" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "84"])
train$avg_travel_time[First.in.District == "85" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "85"])
train$avg_travel_time[First.in.District == "86" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "86"])
train$avg_travel_time[First.in.District == "87" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "87"])
train$avg_travel_time[First.in.District == "88" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "88"])
train$avg_travel_time[First.in.District == "89" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "89"])
train$avg_travel_time[First.in.District == "90" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "90"])
train$avg_travel_time[First.in.District == "91" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "91"])
train$avg_travel_time[First.in.District == "92" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "92"])
train$avg_travel_time[First.in.District == "93" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "93"])
train$avg_travel_time[First.in.District == "94" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "94"])
train$avg_travel_time[First.in.District == "95" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "95"])
train$avg_travel_time[First.in.District == "96" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "96"])
train$avg_travel_time[First.in.District == "97" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "97"])
train$avg_travel_time[First.in.District == "98" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "98"])
train$avg_travel_time[First.in.District == "99" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "99"])
train$avg_travel_time[First.in.District == "100" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "100"])

train$avg_travel_time[First.in.District == "102" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "102"])
train$avg_travel_time[First.in.District == "103" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "103"])
train$avg_travel_time[First.in.District == "104" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "104"])
train$avg_travel_time[First.in.District == "105" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "105"])
train$avg_travel_time[First.in.District == "106" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "106"])
train$avg_travel_time[First.in.District == "107" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "107"])
train$avg_travel_time[First.in.District == "108" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "108"])
train$avg_travel_time[First.in.District == "109" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "109"])
train$avg_travel_time[First.in.District == "110" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "110"])

# Non-EMS
All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS<-as.numeric(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS)
train$avg_travel_time[First.in.District == "1" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "1"])
train$avg_travel_time[First.in.District == "2" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "2"])
train$avg_travel_time[First.in.District == "3" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "3"])
train$avg_travel_time[First.in.District == "4" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "4"])
train$avg_travel_time[First.in.District == "5" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "5"])
train$avg_travel_time[First.in.District == "6" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "6"])
train$avg_travel_time[First.in.District == "7" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "7"])
train$avg_travel_time[First.in.District == "8" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "8"])
train$avg_travel_time[First.in.District == "9" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "9"])
train$avg_travel_time[First.in.District == "10" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "10"])
train$avg_travel_time[First.in.District == "11" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "11"])
train$avg_travel_time[First.in.District == "12" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "12"])
train$avg_travel_time[First.in.District == "13" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "13"])
train$avg_travel_time[First.in.District == "14" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "14"])
train$avg_travel_time[First.in.District == "15" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "15"])
train$avg_travel_time[First.in.District == "16" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "16"])
train$avg_travel_time[First.in.District == "17" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "17"])
train$avg_travel_time[First.in.District == "18" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "18"])
train$avg_travel_time[First.in.District == "19" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "19"])
train$avg_travel_time[First.in.District == "20" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "20"])
train$avg_travel_time[First.in.District == "21" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "21"])

train$avg_travel_time[First.in.District == "23" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "23"])
train$avg_travel_time[First.in.District == "24" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "24"])
train$avg_travel_time[First.in.District == "25" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "25"])
train$avg_travel_time[First.in.District == "26" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "26"])

train$avg_travel_time[First.in.District == "28" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "28"])
train$avg_travel_time[First.in.District == "29" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "29"])

train$avg_travel_time[First.in.District == "33" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "33"])
train$avg_travel_time[First.in.District == "34" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "34"])
train$avg_travel_time[First.in.District == "35" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "35"])
train$avg_travel_time[First.in.District == "36" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "36"])
train$avg_travel_time[First.in.District == "37" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "37"])
train$avg_travel_time[First.in.District == "38" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "38"])
train$avg_travel_time[First.in.District == "39" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "39"])

train$avg_travel_time[First.in.District == "41" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "41"])
train$avg_travel_time[First.in.District == "42" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "42"])
train$avg_travel_time[First.in.District == "43" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "43"])
train$avg_travel_time[First.in.District == "44" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "44"])

train$avg_travel_time[First.in.District == "46" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "46"])
train$avg_travel_time[First.in.District == "47" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "47"])

train$avg_travel_time[First.in.District == "55" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "55"])
train$avg_travel_time[First.in.District == "56" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "56"])
train$avg_travel_time[First.in.District == "57" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "57"])

train$avg_travel_time[First.in.District == "58" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "58"])
train$avg_travel_time[First.in.District == "59" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "59"])
train$avg_travel_time[First.in.District == "60" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "60"])
train$avg_travel_time[First.in.District == "61" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "61"])
train$avg_travel_time[First.in.District == "62" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "62"])
train$avg_travel_time[First.in.District == "63" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "63"])
train$avg_travel_time[First.in.District == "64" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "64"])

train$avg_travel_time[First.in.District == "65" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "65"])
train$avg_travel_time[First.in.District == "66" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "66"])
train$avg_travel_time[First.in.District == "67" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "67"])
train$avg_travel_time[First.in.District == "68" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "68"])
train$avg_travel_time[First.in.District == "69" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "69"])
train$avg_travel_time[First.in.District == "70" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "70"])
train$avg_travel_time[First.in.District == "71" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "71"])
train$avg_travel_time[First.in.District == "72" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "72"])
train$avg_travel_time[First.in.District == "73" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "73"])
train$avg_travel_time[First.in.District == "74" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "74"])
train$avg_travel_time[First.in.District == "75" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "75"])
train$avg_travel_time[First.in.District == "76" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "76"])
train$avg_travel_time[First.in.District == "77" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "77"])

train$avg_travel_time[First.in.District == "78" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "78"])
train$avg_travel_time[First.in.District == "79" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "79"])
train$avg_travel_time[First.in.District == "80" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "80"])

train$avg_travel_time[First.in.District == "81" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "81"])
train$avg_travel_time[First.in.District == "82" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "82"])
train$avg_travel_time[First.in.District == "83" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "83"])
train$avg_travel_time[First.in.District == "84" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "84"])
train$avg_travel_time[First.in.District == "85" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "85"])
train$avg_travel_time[First.in.District == "86" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "86"])
train$avg_travel_time[First.in.District == "87" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "87"])
train$avg_travel_time[First.in.District == "88" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "88"])
train$avg_travel_time[First.in.District == "89" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "89"])
train$avg_travel_time[First.in.District == "90" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "90"])
train$avg_travel_time[First.in.District == "91" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "91"])
train$avg_travel_time[First.in.District == "92" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "92"])
train$avg_travel_time[First.in.District == "93" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "93"])
train$avg_travel_time[First.in.District == "94" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "94"])
train$avg_travel_time[First.in.District == "95" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "95"])
train$avg_travel_time[First.in.District == "96" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "96"])
train$avg_travel_time[First.in.District == "97" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "97"])
train$avg_travel_time[First.in.District == "98" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "98"])
train$avg_travel_time[First.in.District == "99" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "99"])
train$avg_travel_time[First.in.District == "100" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "100"])

train$avg_travel_time[First.in.District == "102" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "102"])
train$avg_travel_time[First.in.District == "103" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "103"])
train$avg_travel_time[First.in.District == "104" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "104"])
train$avg_travel_time[First.in.District == "105" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "105"])
train$avg_travel_time[First.in.District == "106" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "106"])
train$avg_travel_time[First.in.District == "107" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "107"])
train$avg_travel_time[First.in.District == "108" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "108"])
train$avg_travel_time[First.in.District == "109" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "109"])
train$avg_travel_time[First.in.District == "110" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "110"])

# For the Test dataset
avg_travel_time <- rep(NA,length(test$year))
test <- cbind(avg_travel_time,test)

test$avg_travel_time[First.in.District == "1" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "1"])
test$avg_travel_time[First.in.District == "2" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "2"])
test$avg_travel_time[First.in.District == "3" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "3"])
test$avg_travel_time[First.in.District == "4" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "4"])
test$avg_travel_time[First.in.District == "5" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "5"])
test$avg_travel_time[First.in.District == "6" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "6"])
test$avg_travel_time[First.in.District == "7" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "7"])
test$avg_travel_time[First.in.District == "8" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "8"])
test$avg_travel_time[First.in.District == "9" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "9"])
test$avg_travel_time[First.in.District == "10" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "10"])
test$avg_travel_time[First.in.District == "11" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "11"])
test$avg_travel_time[First.in.District == "12" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "12"])
test$avg_travel_time[First.in.District == "13" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "13"])
test$avg_travel_time[First.in.District == "14" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "14"])
test$avg_travel_time[First.in.District == "15" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "15"])
test$avg_travel_time[First.in.District == "16" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "16"])
test$avg_travel_time[First.in.District == "17" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "17"])
test$avg_travel_time[First.in.District == "18" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "18"])
test$avg_travel_time[First.in.District == "19" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "19"])
test$avg_travel_time[First.in.District == "20" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "20"])
test$avg_travel_time[First.in.District == "21" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "21"])

test$avg_travel_time[First.in.District == "23" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "23"])
test$avg_travel_time[First.in.District == "24" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "24"])
test$avg_travel_time[First.in.District == "25" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "25"])
test$avg_travel_time[First.in.District == "26" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "26"])

test$avg_travel_time[First.in.District == "28" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "28"])
test$avg_travel_time[First.in.District == "29" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "29"])

test$avg_travel_time[First.in.District == "33" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "33"])
test$avg_travel_time[First.in.District == "34" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "34"])
test$avg_travel_time[First.in.District == "35" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "35"])
test$avg_travel_time[First.in.District == "36" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "36"])
test$avg_travel_time[First.in.District == "37" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "37"])
test$avg_travel_time[First.in.District == "38" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "38"])
test$avg_travel_time[First.in.District == "39" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "39"])

test$avg_travel_time[First.in.District == "41" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "41"])
test$avg_travel_time[First.in.District == "42" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "42"])
test$avg_travel_time[First.in.District == "43" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "43"])
test$avg_travel_time[First.in.District == "44" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "44"])

test$avg_travel_time[First.in.District == "46" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "46"])
test$avg_travel_time[First.in.District == "47" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "47"])

test$avg_travel_time[First.in.District == "55" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "55"])
test$avg_travel_time[First.in.District == "56" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "56"])
test$avg_travel_time[First.in.District == "57" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "57"])

test$avg_travel_time[First.in.District == "58" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "58"])
test$avg_travel_time[First.in.District == "59" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "59"])
test$avg_travel_time[First.in.District == "60" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "60"])
test$avg_travel_time[First.in.District == "61" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "61"])
test$avg_travel_time[First.in.District == "62" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "62"])
test$avg_travel_time[First.in.District == "63" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "63"])
test$avg_travel_time[First.in.District == "64" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "64"])

test$avg_travel_time[First.in.District == "65" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "65"])
test$avg_travel_time[First.in.District == "66" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "66"])
test$avg_travel_time[First.in.District == "67" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "67"])
test$avg_travel_time[First.in.District == "68" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "68"])
test$avg_travel_time[First.in.District == "69" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "69"])
test$avg_travel_time[First.in.District == "70" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "70"])
test$avg_travel_time[First.in.District == "71" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "71"])
test$avg_travel_time[First.in.District == "72" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "72"])
test$avg_travel_time[First.in.District == "73" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "73"])
test$avg_travel_time[First.in.District == "74" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "74"])
test$avg_travel_time[First.in.District == "75" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "75"])
test$avg_travel_time[First.in.District == "76" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "76"])
test$avg_travel_time[First.in.District == "77" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "77"])

test$avg_travel_time[First.in.District == "78" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "78"])
test$avg_travel_time[First.in.District == "79" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "79"])
test$avg_travel_time[First.in.District == "80" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "80"])

test$avg_travel_time[First.in.District == "81" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "81"])
test$avg_travel_time[First.in.District == "82" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "82"])
test$avg_travel_time[First.in.District == "83" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "83"])
test$avg_travel_time[First.in.District == "84" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "84"])
test$avg_travel_time[First.in.District == "85" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "85"])
test$avg_travel_time[First.in.District == "86" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "86"])
test$avg_travel_time[First.in.District == "87" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "87"])
test$avg_travel_time[First.in.District == "88" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "88"])
test$avg_travel_time[First.in.District == "89" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "89"])
test$avg_travel_time[First.in.District == "90" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "90"])
test$avg_travel_time[First.in.District == "91" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "91"])
test$avg_travel_time[First.in.District == "92" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "92"])
test$avg_travel_time[First.in.District == "93" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "93"])
test$avg_travel_time[First.in.District == "94" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "94"])
test$avg_travel_time[First.in.District == "95" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "95"])
test$avg_travel_time[First.in.District == "96" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "96"])
test$avg_travel_time[First.in.District == "97" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "97"])
test$avg_travel_time[First.in.District == "98" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "98"])
test$avg_travel_time[First.in.District == "99" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "99"])
test$avg_travel_time[First.in.District == "100" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "100"])

test$avg_travel_time[First.in.District == "102" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "102"])
test$avg_travel_time[First.in.District == "103" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "103"])
test$avg_travel_time[First.in.District == "104" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "104"])
test$avg_travel_time[First.in.District == "105" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "105"])
test$avg_travel_time[First.in.District == "106" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "106"])
test$avg_travel_time[First.in.District == "107" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "107"])
test$avg_travel_time[First.in.District == "108" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "108"])
test$avg_travel_time[First.in.District == "109" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "109"])
test$avg_travel_time[First.in.District == "110" & PPE.Level == "EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME.IN.DISTRICT...EMS[DISTRICT == "110"])
#non ems
test$avg_travel_time[First.in.District == "1" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "1"])
test$avg_travel_time[First.in.District == "2" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "2"])
test$avg_travel_time[First.in.District == "3" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "3"])
test$avg_travel_time[First.in.District == "4" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "4"])
test$avg_travel_time[First.in.District == "5" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "5"])
test$avg_travel_time[First.in.District == "6" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "6"])
test$avg_travel_time[First.in.District == "7" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "7"])
test$avg_travel_time[First.in.District == "8" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "8"])
test$avg_travel_time[First.in.District == "9" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "9"])
test$avg_travel_time[First.in.District == "10" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "10"])
test$avg_travel_time[First.in.District == "11" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "11"])
test$avg_travel_time[First.in.District == "12" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "12"])
test$avg_travel_time[First.in.District == "13" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "13"])
test$avg_travel_time[First.in.District == "14" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "14"])
test$avg_travel_time[First.in.District == "15" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "15"])
test$avg_travel_time[First.in.District == "16" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "16"])
test$avg_travel_time[First.in.District == "17" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "17"])
test$avg_travel_time[First.in.District == "18" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "18"])
test$avg_travel_time[First.in.District == "19" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "19"])
test$avg_travel_time[First.in.District == "20" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "20"])
test$avg_travel_time[First.in.District == "21" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "21"])

test$avg_travel_time[First.in.District == "23" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "23"])
test$avg_travel_time[First.in.District == "24" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "24"])
test$avg_travel_time[First.in.District == "25" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "25"])
test$avg_travel_time[First.in.District == "26" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "26"])

test$avg_travel_time[First.in.District == "28" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "28"])
test$avg_travel_time[First.in.District == "29" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "29"])

test$avg_travel_time[First.in.District == "33" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "33"])
test$avg_travel_time[First.in.District == "34" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "34"])
test$avg_travel_time[First.in.District == "35" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "35"])
test$avg_travel_time[First.in.District == "36" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "36"])
test$avg_travel_time[First.in.District == "37" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "37"])
test$avg_travel_time[First.in.District == "38" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "38"])
test$avg_travel_time[First.in.District == "39" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "39"])

test$avg_travel_time[First.in.District == "41" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "41"])
test$avg_travel_time[First.in.District == "42" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "42"])
test$avg_travel_time[First.in.District == "43" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "43"])
test$avg_travel_time[First.in.District == "44" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "44"])

test$avg_travel_time[First.in.District == "46" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "46"])
test$avg_travel_time[First.in.District == "47" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "47"])

test$avg_travel_time[First.in.District == "55" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "55"])
test$avg_travel_time[First.in.District == "56" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "56"])
test$avg_travel_time[First.in.District == "57" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "57"])

test$avg_travel_time[First.in.District == "58" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "58"])
test$avg_travel_time[First.in.District == "59" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "59"])
test$avg_travel_time[First.in.District == "60" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "60"])
test$avg_travel_time[First.in.District == "61" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "61"])
test$avg_travel_time[First.in.District == "62" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "62"])
test$avg_travel_time[First.in.District == "63" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "63"])
test$avg_travel_time[First.in.District == "64" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "64"])

test$avg_travel_time[First.in.District == "65" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "65"])
test$avg_travel_time[First.in.District == "66" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "66"])
test$avg_travel_time[First.in.District == "67" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "67"])
test$avg_travel_time[First.in.District == "68" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "68"])
test$avg_travel_time[First.in.District == "69" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "69"])
test$avg_travel_time[First.in.District == "70" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "70"])
test$avg_travel_time[First.in.District == "71" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "71"])
test$avg_travel_time[First.in.District == "72" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "72"])
test$avg_travel_time[First.in.District == "73" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "73"])
test$avg_travel_time[First.in.District == "74" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "74"])
test$avg_travel_time[First.in.District == "75" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "75"])
test$avg_travel_time[First.in.District == "76" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "76"])
test$avg_travel_time[First.in.District == "77" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "77"])

test$avg_travel_time[First.in.District == "78" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "78"])
test$avg_travel_time[First.in.District == "79" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "79"])
test$avg_travel_time[First.in.District == "80" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "80"])

test$avg_travel_time[First.in.District == "81" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "81"])
test$avg_travel_time[First.in.District == "82" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "82"])
test$avg_travel_time[First.in.District == "83" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "83"])
test$avg_travel_time[First.in.District == "84" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "84"])
test$avg_travel_time[First.in.District == "85" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "85"])
test$avg_travel_time[First.in.District == "86" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "86"])
test$avg_travel_time[First.in.District == "87" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "87"])
test$avg_travel_time[First.in.District == "88" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "88"])
test$avg_travel_time[First.in.District == "89" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "89"])
test$avg_travel_time[First.in.District == "90" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "90"])
test$avg_travel_time[First.in.District == "91" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "91"])
test$avg_travel_time[First.in.District == "92" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "92"])
test$avg_travel_time[First.in.District == "93" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "93"])
test$avg_travel_time[First.in.District == "94" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "94"])
test$avg_travel_time[First.in.District == "95" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "95"])
test$avg_travel_time[First.in.District == "96" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "96"])
test$avg_travel_time[First.in.District == "97" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "97"])
test$avg_travel_time[First.in.District == "98" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "98"])
test$avg_travel_time[First.in.District == "99" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "99"])
test$avg_travel_time[First.in.District == "100" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "100"])

test$avg_travel_time[First.in.District == "102" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "102"])
test$avg_travel_time[First.in.District == "103" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "103"])
test$avg_travel_time[First.in.District == "104" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "104"])
test$avg_travel_time[First.in.District == "105" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "105"])
test$avg_travel_time[First.in.District == "106" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "106"])
test$avg_travel_time[First.in.District == "107" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "107"])
test$avg_travel_time[First.in.District == "108" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "108"])
test$avg_travel_time[First.in.District == "109" & PPE.Level == "Non-EMS"] <- median(All_Stations_Response_Metrics_._2016$AVERAGE.LAFD.TRAVEL.TIME..IN.DISTRICT...Non.EMS[DISTRICT == "109"])
test$avg_travel_time[First.in.District == "110" & PPE.L

# We also include all the zip-code of the each firestation 
# Train Zip-code
train$zip_code[train$First.in.District == "1"] <- 90031
train$zip_code[train$First.in.District == "2"] <- 90033
train$zip_code[train$First.in.District == "3"] <- 90012
train$zip_code[train$First.in.District == "4"] <- 90012
train$zip_code[train$First.in.District == "5"] <- 90045
train$zip_code[train$First.in.District == "6"] <- 90004
train$zip_code[train$First.in.District == "7"] <- 91402
train$zip_code[train$First.in.District == "8"] <- 91326
train$zip_code[train$First.in.District == "9"] <- 90023
train$zip_code[train$First.in.District == "10"] <- 90015
train$zip_code[train$First.in.District == "11"] <- 90057
train$zip_code[train$First.in.District == "12"] <- 90042
train$zip_code[train$First.in.District == "13"] <- 90006
train$zip_code[train$First.in.District == "14"] <- 90011
train$zip_code[train$First.in.District == "15"] <- 90007
train$zip_code[train$First.in.District == "16"] <- 90032
train$zip_code[train$First.in.District == "17"] <- 90021
train$zip_code[train$First.in.District == "18"] <- 91342
train$zip_code[train$First.in.District == "19"] <- 90049
train$zip_code[train$First.in.District == "20"] <- 90026
train$zip_code[train$First.in.District == "21"] <- 90011

train$zip_code[train$First.in.District == "23"] <- 90272
train$zip_code[train$First.in.District == "24"] <- 91040
train$zip_code[train$First.in.District == "25"] <- 90023
train$zip_code[train$First.in.District == "26"] <- 90018

train$zip_code[train$First.in.District == "28"] <- 91326
train$zip_code[train$First.in.District == "29"] <- 90010

train$zip_code[train$First.in.District == "33"] <- 90003
train$zip_code[train$First.in.District == "34"] <- 90018
train$zip_code[train$First.in.District == "35"] <- 90039
train$zip_code[train$First.in.District == "36"] <- 90731
train$zip_code[train$First.in.District == "37"] <- 90024
train$zip_code[train$First.in.District == "38"] <- 90744
train$zip_code[train$First.in.District == "39"] <- 91401

train$zip_code[train$First.in.District == "41"] <- 90046
train$zip_code[train$First.in.District == "42"] <- 90041
train$zip_code[train$First.in.District == "43"] <- 90034
train$zip_code[train$First.in.District == "44"] <- 90065

train$zip_code[train$First.in.District == "46"] <- 90037
train$zip_code[train$First.in.District == "47"] <- 90032

train$zip_code[train$First.in.District == "49"] <- 90744
train$zip_code[train$First.in.District == "50"] <- 90065
train$zip_code[train$First.in.District == "51"] <- 91345
train$zip_code[train$First.in.District == "52"] <- 90029

train$zip_code[train$First.in.District == "55"] <- 90041
train$zip_code[train$First.in.District == "56"] <- 90065
train$zip_code[train$First.in.District == "57"] <- 90003

train$zip_code[train$First.in.District == "58"] <- 90035
train$zip_code[train$First.in.District == "59"] <- 90064
train$zip_code[train$First.in.District == "60"] <- 91601
train$zip_code[train$First.in.District == "61"] <- 90036
train$zip_code[train$First.in.District == "62"] <- 90066
train$zip_code[train$First.in.District == "63"] <- 90291
train$zip_code[train$First.in.District == "64"] <- 90061

train$zip_code[train$First.in.District == "65"] <- 90002
train$zip_code[train$First.in.District == "66"] <- 90037
train$zip_code[train$First.in.District == "67"] <- 90045
train$zip_code[train$First.in.District == "68"] <- 90040
train$zip_code[train$First.in.District == "69"] <- 90272
train$zip_code[train$First.in.District == "70"] <- 91324
train$zip_code[train$First.in.District == "71"] <- 90024
train$zip_code[train$First.in.District == "72"] <- 91303
train$zip_code[train$First.in.District == "73"] <- 91335
train$zip_code[train$First.in.District == "74"] <- 91040
train$zip_code[train$First.in.District == "75"] <- 91345
train$zip_code[train$First.in.District == "76"] <- 90068

train$zip_code[train$First.in.District == "77"] <- 91604
train$zip_code[train$First.in.District == "78"] <- 91604
train$zip_code[train$First.in.District == "79"] <- 90248

train$zip_code[train$First.in.District == "80"] <- 91345
train$zip_code[train$First.in.District == "81"] <- 91402
train$zip_code[train$First.in.District == "82"] <- 90028
train$zip_code[train$First.in.District == "83"] <- 91316
train$zip_code[train$First.in.District == "84"] <- 91367
train$zip_code[train$First.in.District == "85"] <- 90710

train$zip_code[train$First.in.District == "86"] <- 90068
train$zip_code[train$First.in.District == "87"] <- 91344
train$zip_code[train$First.in.District == "88"] <- 91403
train$zip_code[train$First.in.District == "89"] <- 91605

train$zip_code[train$First.in.District == "90"] <- 91406
train$zip_code[train$First.in.District == "91"] <- 91342
train$zip_code[train$First.in.District == "92"] <- 90064
train$zip_code[train$First.in.District == "93"] <- 91356
train$zip_code[train$First.in.District == "94"] <- 90016
train$zip_code[train$First.in.District == "95"] <- 90045
train$zip_code[train$First.in.District == "96"] <- 91311
train$zip_code[train$First.in.District == "97"] <- 91604
train$zip_code[train$First.in.District == "98"] <- 91331
train$zip_code[train$First.in.District == "99"] <- 91604
train$zip_code[train$First.in.District == "100"] <- 91406

train$zip_code[train$First.in.District == "102"] <- 91401
train$zip_code[train$First.in.District == "103"] <- 91325
train$zip_code[train$First.in.District == "104"] <- 91306
train$zip_code[train$First.in.District == "105"] <- 91367
train$zip_code[train$First.in.District == "106"] <- 91304
train$zip_code[train$First.in.District == "107"] <- 91311
train$zip_code[train$First.in.District == "108"] <- 90210
train$zip_code[train$First.in.District == "109"] <- 90049
train$zip_code[train$First.in.District == "110"] <- 90731
train$zip_code[train$First.in.District == "112"] <- 90744

# For the test dataset
test$zip_code <- rep(NA,length(test$year))

test$zip_code[test$First.in.District == "1"] <- 90031
test$zip_code[test$First.in.District == "2"] <- 90033
test$zip_code[test$First.in.District == "3"] <- 90012
test$zip_code[test$First.in.District == "4"] <- 90012
test$zip_code[test$First.in.District == "5"] <- 90045
test$zip_code[test$First.in.District == "6"] <- 90004
test$zip_code[test$First.in.District == "7"] <- 91402
test$zip_code[test$First.in.District == "8"] <- 91326
test$zip_code[test$First.in.District == "9"] <- 90023
test$zip_code[test$First.in.District == "10"] <- 90015
test$zip_code[test$First.in.District == "11"] <- 90057
test$zip_code[test$First.in.District == "12"] <- 90042
test$zip_code[test$First.in.District == "13"] <- 90006
test$zip_code[test$First.in.District == "14"] <- 90011
test$zip_code[test$First.in.District == "15"] <- 90007
test$zip_code[test$First.in.District == "16"] <- 90032
test$zip_code[test$First.in.District == "17"] <- 90021
test$zip_code[test$First.in.District == "18"] <- 91342
test$zip_code[test$First.in.District == "19"] <- 90049
test$zip_code[test$First.in.District == "20"] <- 90026
test$zip_code[test$First.in.District == "21"] <- 90011

test$zip_code[test$First.in.District == "23"] <- 90272
test$zip_code[test$First.in.District == "24"] <- 91040
test$zip_code[test$First.in.District == "25"] <- 90023
test$zip_code[test$First.in.District == "26"] <- 90018

test$zip_code[test$First.in.District == "28"] <- 91326
test$zip_code[test$First.in.District == "29"] <- 90010

test$zip_code[test$First.in.District == "33"] <- 90003
test$zip_code[test$First.in.District == "34"] <- 90018
test$zip_code[test$First.in.District == "35"] <- 90039
test$zip_code[test$First.in.District == "36"] <- 90731
test$zip_code[test$First.in.District == "37"] <- 90024
test$zip_code[test$First.in.District == "38"] <- 90744
test$zip_code[test$First.in.District == "39"] <- 91401

test$zip_code[test$First.in.District == "41"] <- 90046
test$zip_code[test$First.in.District == "42"] <- 90041
test$zip_code[test$First.in.District == "43"] <- 90034
test$zip_code[test$First.in.District == "44"] <- 90065

test$zip_code[test$First.in.District == "46"] <- 90037
test$zip_code[test$First.in.District == "47"] <- 90032

test$zip_code[test$First.in.District == "49"] <- 90744
test$zip_code[test$First.in.District == "50"] <- 90065
test$zip_code[test$First.in.District == "51"] <- 91345
test$zip_code[test$First.in.District == "52"] <- 90029

test$zip_code[test$First.in.District == "55"] <- 90041
test$zip_code[test$First.in.District == "56"] <- 90065
test$zip_code[test$First.in.District == "57"] <- 90003

test$zip_code[test$First.in.District == "58"] <- 90035
test$zip_code[test$First.in.District == "59"] <- 90064
test$zip_code[test$First.in.District == "60"] <- 91601
test$zip_code[test$First.in.District == "61"] <- 90036
test$zip_code[test$First.in.District == "62"] <- 90066
test$zip_code[test$First.in.District == "63"] <- 90291
test$zip_code[test$First.in.District == "64"] <- 90061

test$zip_code[test$First.in.District == "65"] <- 90002
test$zip_code[test$First.in.District == "66"] <- 90037
test$zip_code[test$First.in.District == "67"] <- 90045
test$zip_code[test$First.in.District == "68"] <- 90040
test$zip_code[test$First.in.District == "69"] <- 90272
test$zip_code[test$First.in.District == "70"] <- 91324
test$zip_code[test$First.in.District == "71"] <- 90024
test$zip_code[test$First.in.District == "72"] <- 91303
test$zip_code[test$First.in.District == "73"] <- 91335
test$zip_code[test$First.in.District == "74"] <- 91040
test$zip_code[test$First.in.District == "75"] <- 91345
test$zip_code[test$First.in.District == "76"] <- 90068

test$zip_code[test$First.in.District == "77"] <- 91604
test$zip_code[test$First.in.District == "78"] <- 91604
test$zip_code[test$First.in.District == "79"] <- 90248

test$zip_code[test$First.in.District == "80"] <- 91345
test$zip_code[test$First.in.District == "81"] <- 91402
test$zip_code[test$First.in.District == "82"] <- 90028
test$zip_code[test$First.in.District == "83"] <- 91316
test$zip_code[test$First.in.District == "84"] <- 91367
test$zip_code[test$First.in.District == "85"] <- 90710

test$zip_code[test$First.in.District == "86"] <- 90068
test$zip_code[test$First.in.District == "87"] <- 91344
test$zip_code[test$First.in.District == "88"] <- 91403
test$zip_code[test$First.in.District == "89"] <- 91605

test$zip_code[test$First.in.District == "90"] <- 91406
test$zip_code[test$First.in.District == "91"] <- 91342
test$zip_code[test$First.in.District == "92"] <- 90064
test$zip_code[test$First.in.District == "93"] <- 91356
test$zip_code[test$First.in.District == "94"] <- 90016
test$zip_code[test$First.in.District == "95"] <- 90045
test$zip_code[test$First.in.District == "96"] <- 91311
test$zip_code[test$First.in.District == "97"] <- 91604
test$zip_code[test$First.in.District == "98"] <- 91331
test$zip_code[test$First.in.District == "99"] <- 91604
test$zip_code[test$First.in.District == "100"] <- 91406

test$zip_code[test$First.in.District == "102"] <- 91401
test$zip_code[test$First.in.District == "103"] <- 91325
test$zip_code[test$First.in.District == "104"] <- 91306
test$zip_code[test$First.in.District == "105"] <- 91367
test$zip_code[test$First.in.District == "106"] <- 91304
test$zip_code[test$First.in.District == "107"] <- 91311
test$zip_code[test$First.in.District == "108"] <- 90210
test$zip_code[test$First.in.District == "109"] <- 90049
test$zip_code[test$First.in.District == "110"] <- 90731

test$zip_code[test$First.in.District == "112"] <- 90744

# With cleaned dataset, we tried 
#(1) Extreme Gradient Boosting & Cross validation
require(xgboost)
require(methods)
require(data.table)

dtrain = xgb.DMatrix(data.matrix(train[, -c(1:2)]), label=train$elapsed_time)
dvalid = xgb.DMatrix(data.matrix(valid[, -c(1:2)]), label=valid$elapsed_time)
dtest <- xgb.DMatrix(data.matrix(df_test[, -c(1:2)]))
# depth 6~16, #eta = 0.1 ~ 0.01, nround
xg.train <- xgb.train(data=dtrain, 
                      eta=0.1,
                      booster="gbtree", 
                      max.depth=6, 
                      verbose=2,
                      nthread=4, 
                      nround=100, 
                      metrics='rmse',
                      watchlist=list(train=dtrain, valid=dvalid), 
                      eval.metric="rmse", 
                      objective="reg:linear")
p.xg.valid = predict(xg.train, dvalid)
p.xg.valid = pmax(0, p.xg.valid)
mse(valid$elapsed_time - p.xg.valid)

dtrain = xgb.DMatrix(data.matrix(df_train[, -c(1:2)]), label=df_train$elapsed_time)
xg.model <- xgb.train(data=dtrain, 
                      eta=0.1,
                      booster="gbtree", 
                      max.depth=6, 
                      verbose=2,
                      nthread=4, 
                      nround=100, 
                      metrics='rmse',
                      watchlist=list(train=dtrain), 
                      eval.metric="rmse", 
                      objective="reg:linear")
p.xg.test = predict(xg.model, dtest)
head(p.xg.test)
p.xg.test = pmax(0, p.xg.test)

write_submission(p.xg.test, df_test$row.id, 'predict_xg_with_new_df.csv')

# (2) Random Forest
library("randomForest")
rf.train = randomForest(elapsed_time ~ . -`Non-EMS`, data=train[, -c(1:3)],
                         importance=F,
                         do.trace=TRUE,
                         ntree=50)
 p.rf.valid = predict(rf.train, valid[, -c(1:3)])
 mse(valid$elapsed_time - p.rf.valid)
 rf.model = randomForest(elapsed_time ~ . -`Non-EMS`, data=df_train[, -c(1:3)],
                         importance=F,
                         do.trace=TRUE,
                         ntree=50)
 p.rf.test = predict(rf.model, df_test[, -c(1:3)])
 write_submission(p.rf.test, df_test$row.id, 'predict_rf.csv')
# (3) Nerual network deep learning 
library("neuralnet")
nnd <- neuralnet(`elapsed_time` ~ `year` + `Dispatch Sequence` + 
                         `Dispatch Status` + `Unit Type` + `PPE Level` + 
                         `Incident Creation Time (GMT)` + `First in District`  
                 ,data = new, hidden = c(5,3),linear.output = T)
plot(nnd)
nnd$result.matrix
nn_pred = prediction(nnd)
pr.nn <- nn_pred$net.result*(max(df_train$elapsed_time)-min(df_train$elapsed_time))+
        min(df_train$elapsed_time)
# (4) We believed that EMS is a importatant factor so we include interaction
# between EMS with all the variables.
# Linear Regression (Interaction)  
n <- names(df_train)
f <- as.formula(paste("elapsed_time ~", paste(n[!n %in% "elapsed_time"], collapse = " + ")))
df_t <- df_test[,-c(1:3)]
lr.model <- lm(elapsed_time ~ X2013 + X2014 + X2015 + X2016 + norm_First_District + 
                       norm_Dispatch_Seq + AVI + CAV + ENR + HSP + NAV + ONS + OVD + 
                       PGR + QTR + RAD + TSP + WRS + AR + AU + Administrative + 
                       BC + BP + BT + CP + CR + CT + CV + DC + DP + DT + DZ + E + 
                       EA + EL + EM + F + FC + FT + GT + H + HC + HM + HR + PT + 
                       RA + RA6xx + RA8xx + RH + RP + RT + S + SC + SQ + SW + T + 
                       TP + UR + WT + EMS + Non.EMS + FD26028 + FD26029 + norm_Incident_Time + 
                       AVI*EMS + CAV*EMS + ENR*EMS + HSP*EMS + NAV*EMS + ONS*EMS + OVD*EMS + 
                       PGR*EMS + QTR*EMS + RAD*EMS + TSP*EMS + WRS*EMS + AR*EMS + AU*EMS + Administrative*EMS + 
                       BC*EMS + BP*EMS + BT*EMS + CP*EMS + CR*EMS + CT*EMS + CV*EMS + DC*EMS + DP*EMS + DT*EMS + DZ*EMS + E*EMS + 
                       EA*EMS + EL*EMS + EM*EMS + F*EMS + FC*EMS + FT*EMS + GT*EMS + H*EMS + HC*EMS + HM*EMS + HR*EMS + PT*EMS + 
                       RA *EMS+ RA6xx*EMS + RA8xx*EMS + RH*EMS + RP*EMS + RT*EMS + S*EMS + SC*EMS + SQ*EMS + SW*EMS + T*EMS + 
                       TP*EMS + UR*EMS + WT*EMS+ AVI*Non.EMS + CAV*Non.EMS + ENR *Non.EMS+ HSP*Non.EMS + NAV*Non.EMS + ONS*Non.EMS + OVD*Non.EMS + 
                       PGR *Non.EMS+ QTR*Non.EMS + RAD*Non.EMS + TSP*Non.EMS + WRS *Non.EMS+ AR *Non.EMS+ AU *Non.EMS+ Administrative*Non.EMS + 
                       BC*Non.EMS + BP *Non.EMS+ BT*Non.EMS + CP*Non.EMS + CR *Non.EMS+ CT *Non.EMS+ CV *Non.EMS+ DC*Non.EMS + DP *Non.EMS+ DT *Non.EMS+ DZ*Non.EMS + E*Non.EMS + 
                       EA *Non.EMS+ EL*Non.EMS + EM *Non.EMS+ F *Non.EMS+ FC *Non.EMS+ FT *Non.EMS+ GT *Non.EMS+ H *Non.EMS+ HC*Non.EMS + HM*Non.EMS + HR*Non.EMS + PT*Non.EMS + 
                       RA *Non.EMS+ RA6xx *Non.EMS+ RA8xx *Non.EMS+ RH*Non.EMS + RP*Non.EMS + RT *Non.EMS+ S *Non.EMS+ SC*Non.EMS + SQ*Non.EMS + SW *Non.EMS+ T*Non.EMS + 
                       TP *Non.EMS+ UR *Non.EMS+ WT*Non.EMS,data = df) 
anova(lr.model)

# Since we achieved Low MSE when we used GBM and Linear regression with the
# polynomial degree of 5, we treid ensemble of 2 tecniques.
# We gave 70% weight to gradient boosting and 30% weight to the lm+polynomial regression.
# lm + gbm (weighted)
pred_out <- predict(lm_out,df_t)
predTest <- predict(bst, dtest)
ensem<-pred_out*.3+predTest*.7
head(ensem)
setwd("/Users/junhyukjang/Desktop")
df_submit <- data.frame(df_test$row.id, pred_lm)
names(df_submit) <- c("row.id", "prediction")
write.csv(x = df_submit, file = 'prediction_infinite_lm.csv',row.names=FALSE)
length(ensem)
prediction_ensemble <- read.csv("~/Desktop/Submission/prediction_ensemble.csv")


```






